export const bList = [
  {
    "boardSeq":'1',
    "groupMember":{
      "nickname":'String',
      "agree":'String',
      "score":'Int'
    },
    "content":'내용내용11'
  },
  {
    "boardSeq":'2',
    "groupMember":{
      "nickname":'String',
      "agree":'String',
      "score":'Int'
    },
    "content":'내용내용22'
  },
  {
    "boardSeq":'3',
    "groupMember":{
      "nickname":'String',
      "agree":'String',
      "score":'Int'
    },
    "content":'내용내용33'
  },
  {
    "boardSeq":'4',
    "groupMember":{
      "nickname":'String',
      "agree":'String',
      "score":'Int'
    },
    "content":'내용내용44'
  },
  {
    "boardSeq":'5',
    "groupMember":{
      "nickname":'String',
      "agree":'String',
      "score":'Int'
    },
    "content":'내용내용55'
  },
  {
    "boardSeq":'6',
    "groupMember":{
      "nickname":'String',
      "agree":'String',
      "score":'Int'
    },
    "content":'내용내용66'
  },
  {
    "boardSeq":'7',
    "groupMember":{
      "nickname":'String',
      "agree":'String',
      "score":'Int'
    },
    "content":'내용내용77'
  },
  {
    "boardSeq":'8',
    "groupMember":{
      "nickname":'String',
      "agree":'String',
      "score":'Int'
    },
    "content":'내용내용88'
  },
  {
    "boardSeq":'9',
    "groupMember":{
      "nickname":'String',
      "agree":'String',
      "score":'Int'
    },
    "content":'내용내용99'
  },
];