export { default as CreateGroup } from './CreateGroup/CreateGroup'
export { default as Home } from './Home/Home'
export { default as Memory} from './Memory/Memory'
export { default as MemoryList } from './MemoryList/MemoryList'
export { default as Quiz } from './Quiz/Quiz'
